export enum WellType {
  EXPLORATION = 'EXPLORATION',
  DEVELOPMENT = 'DEVELOPMENT',
  APPRAISAL = 'APPRAISAL',
  WILDCAT = 'WILDCAT',
  STRATIGRAPHIC = 'STRATIGRAPHIC',
}

export enum WellStatus {
  PLANNED = 'PLANNED',
  DRILLING = 'DRILLING',
  COMPLETED = 'COMPLETED',
  SUSPENDED = 'SUSPENDED',
  ABANDONED = 'ABANDONED',
}

export enum EventType {
  LOST_CIRCULATION = 'LOST_CIRCULATION',
  KICK = 'KICK',
  STUCK_PIPE = 'STUCK_PIPE',
  FISHING = 'FISHING',
  NPT = 'NPT',
  TORQUE_SPIKE = 'TORQUE_SPIKE',
  PRESSURE_ANOMALY = 'PRESSURE_ANOMALY',
  FORMATION_INSTABILITY = 'FORMATION_INSTABILITY',
  CASING_EVENT = 'CASING_EVENT',
  CEMENTING_EVENT = 'CEMENTING_EVENT',
  EQUIPMENT_FAILURE = 'EQUIPMENT_FAILURE',
  OTHER = 'OTHER',
}

export enum EventSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum QualityStatus {
  VALID = 'VALID',
  WARNING = 'WARNING',
  INVALID = 'INVALID',
  UNVERIFIED = 'UNVERIFIED',
  VERIFIED = 'VERIFIED',
}

export enum DocumentType {
  WCR = 'WCR', // Well Completion Report
  DDR = 'DDR', // Daily Drilling Report
  MUD_REPORT = 'MUD_REPORT',
  GEOLOGICAL_REPORT = 'GEOLOGICAL_REPORT',
  CEMENTING_REPORT = 'CEMENTING_REPORT',
  CASING_REPORT = 'CASING_REPORT',
  DRILLING_REPORT = 'DRILLING_REPORT',
  INCIDENT_REPORT = 'INCIDENT_REPORT',
  OTHER = 'OTHER',
}

export enum DocumentProcessingStatus {
  UPLOADED = 'UPLOADED',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  TEXT_EXTRACTION = 'TEXT_EXTRACTION',
  OCR_PROCESSING = 'OCR_PROCESSING',
  CHUNKING = 'CHUNKING',
  ENTITY_EXTRACTION = 'ENTITY_EXTRACTION',
  EVENT_EXTRACTION = 'EVENT_EXTRACTION',
  EMBEDDING = 'EMBEDDING',
  PROCESSED = 'PROCESSED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  VERIFIED = 'VERIFIED',
  VERIFICATION_REQUIRED = 'VERIFICATION_REQUIRED',
}

export enum DataSourceType {
  SYNTHETIC = 'SYNTHETIC',
  CSV = 'CSV',
  EXCEL = 'EXCEL',
  WITSML = 'WITSML',
  ERTMAC = 'ERTMAC',
  DOCUMENT = 'DOCUMENT',
  API = 'API',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  DRILLING_ENGINEER = 'DRILLING_ENGINEER',
  GEOLOGIST = 'GEOLOGIST',
  MANAGER = 'MANAGER',
  DATA_ENGINEER = 'DATA_ENGINEER',
  VIEWER = 'VIEWER',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  DATA_IMPORT = 'DATA_IMPORT',
  DATA_UPDATE = 'DATA_UPDATE',
  DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD',
  EVENT_UPDATE = 'EVENT_UPDATE',
  USER_UPDATE = 'USER_UPDATE',
}
