/**
 * Centralized Configuration for NWIS Real-Time Intelligence & Risk Engines
 * Strictly no magic numbers across detection, features, and risk scoring.
 */

export const FEATURE_WINDOWS = {
  SHORT_SECONDS: 30,
  MEDIUM_SECONDS: 60,
  LONG_SECONDS: 300,
  EXTENDED_SECONDS: 900,
} as const;

export const SENSOR_BOUNDS = {
  ROP: { MIN: 0, MAX: 150, UNIT: 'm/hr' },
  WOB: { MIN: 0, MAX: 400, UNIT: 'kN' },
  RPM: { MIN: 0, MAX: 250, UNIT: 'rpm' },
  TORQUE: { MIN: 0, MAX: 60, UNIT: 'kNm' },
  STANDPIPE_PRESSURE: { MIN: 0, MAX: 450, UNIT: 'bar' },
  FLOW_IN: { MIN: 0, MAX: 5000, UNIT: 'L/min' },
  FLOW_OUT: { MIN: 0, MAX: 5000, UNIT: 'L/min' },
  MUD_WEIGHT: { MIN: 0.8, MAX: 2.5, UNIT: 'sg' },
  HOOKLOAD: { MIN: 0, MAX: 3500, UNIT: 'kN' },
  DRAG: { MIN: -100, MAX: 500, UNIT: 'kN' },
} as const;

export const ANOMALY_THRESHOLDS = {
  // Statistical z-score thresholds
  Z_SCORE_WATCH: 2.0,
  Z_SCORE_WARNING: 2.8,
  Z_SCORE_CRITICAL: 3.5,

  // Robust z-score thresholds
  ROBUST_Z_WATCH: 2.2,
  ROBUST_Z_WARNING: 3.0,
  ROBUST_Z_CRITICAL: 4.0,

  // Percentage deviations from baseline
  TORQUE_INCREASE_PCT_WATCH: 15.0,
  TORQUE_INCREASE_PCT_WARNING: 25.0,
  TORQUE_INCREASE_PCT_CRITICAL: 40.0,

  ROP_DECREASE_PCT_WATCH: 15.0,
  ROP_DECREASE_PCT_WARNING: 25.0,
  ROP_DECREASE_PCT_CRITICAL: 50.0,

  DRAG_INCREASE_PCT_WATCH: 12.0,
  DRAG_INCREASE_PCT_WARNING: 20.0,
  DRAG_INCREASE_PCT_CRITICAL: 35.0,

  FLOW_DIFF_LPM_WATCH: 150.0,
  FLOW_DIFF_LPM_WARNING: 300.0,
  FLOW_DIFF_LPM_CRITICAL: 600.0,

  PIT_VOLUME_CHANGE_M3_WATCH: 1.5,
  PIT_VOLUME_CHANGE_M3_WARNING: 3.0,
  PIT_VOLUME_CHANGE_M3_CRITICAL: 6.0,
} as const;

export const RISK_SCORE_BOUNDS = {
  NORMAL: { MIN: 0, MAX: 30 },
  WATCH: { MIN: 31, MAX: 60 },
  WARNING: { MIN: 61, MAX: 80 },
  CRITICAL: { MIN: 81, MAX: 100 },
} as const;

export const RISK_WEIGHTS = {
  STUCK_PIPE: {
    TORQUE_TREND: 24,
    ROP_DECLINE: 18,
    DRAG_INCREASE: 14,
    HISTORICAL_PRECEDENT: 20,
    FORMATION_CONTEXT: 12,
    HOOKLOAD_INSTABILITY: 12,
  },
  LOST_CIRCULATION: {
    FLOW_OUT_DEFICIT: 35,
    PIT_VOLUME_LOSS: 25,
    PRESSURE_DROP: 15,
    FORMATION_PERMEABILITY: 15,
    HISTORICAL_PRECEDENT: 10,
  },
  KICK: {
    FLOW_OUT_SURGE: 35,
    PIT_VOLUME_GAIN: 25,
    PRESSURE_DROP_SPP: 15,
    GAS_SHOW_OR_TEMP: 10,
    HISTORICAL_PRECEDENT: 15,
  },
  TORQUE_ANOMALY: {
    TORQUE_MAGNITUDE: 40,
    TORQUE_OSCILLATION: 25,
    RPM_RESPONSE: 20,
    FORMATION_BASELINE: 15,
  },
  CEMENTING: {
    DISPLACEMENT_PRESSURE: 35,
    VOLUME_DISCREPANCY: 30,
    RETURN_FLOW_ANOMALY: 20,
    HISTORICAL_JOB_DEVIATION: 15,
  },
} as const;

export const PRECEDENT_WEIGHTS = {
  FORMATION_SIMILARITY: 0.25,
  DEPTH_SIMILARITY: 0.15,
  TRAJECTORY_SIMILARITY: 0.10,
  SPATIAL_SIMILARITY: 0.10,
  OPERATIONAL_SIMILARITY: 0.15,
  FEATURE_SIMILARITY: 0.25,
} as const;

export const ALERT_LIFECYCLE = {
  DEDUPLICATION_WINDOW_SECONDS: 60,
  COOLDOWN_SECONDS: 120,
  DEBOUNCE_SAMPLES_FOR_RESOLUTION: 4, // 4 consecutive normal samples required to auto-resolve
  MINIMUM_SAMPLES_FOR_FEATURE_WINDOW: 3,
  SENSOR_STALE_THRESHOLD_SECONDS: 30,
} as const;

export const SIMULATION_PRESETS = {
  DEFAULT_WELL_ID: 'OIL-SYN-020',
  DEFAULT_START_DEPTH: 3200,
  DEFAULT_END_DEPTH: 3250,
  DEFAULT_INTERVAL_SECONDS: 2,
  DEFAULT_SPEED_MULTIPLIER: 5,
} as const;
